### ISSUE TITLE
missing required packages inside examples/ dir

### ISSUE THREAD

**Issue by alcipir** [Bitcoin-com/cashscript#36]
- Steps to reproduce this bug:
```
npm install -g ts-node
git clone https://github.com/Bitcoin-com/cashscript
cd cashscript/examples
npm install
ts-node p2pkh.ts
```
- Error ouput:
```
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/lib/node_modules/ts-node/dist/index.js
- /usr/lib/node_modules/ts-node/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.register (/usr/lib/node_modules/ts-node/dist/index.js:138:30)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/dist/bin.js:94:25)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/ts-node/dist/index.js',
    '/usr/lib/node_modules/ts-node/dist/bin.js'
  ]
}
```
Am I doing something wrong here? I solved it by adding typescript and @types/node to the package.json file inside examples/ directory:

```
{
  "name": "cashscript-examples",
  "version": "1.0.0",
  "description": "Usage examples of the CashScript SDK",
  "main": "p2pkh.js",
  "author": "Rosco Kalis <rosco@bitcoin.com>",
  "license": "MIT",
  "dependencies": {
    "bitbox-sdk": "^8.4.0",
    "bitcoincashjs-lib": "Bitcoin-com/bitcoincashjs-lib#v4.0.1",
    "cashscript": "^0.2.1-beta",
    "@types/node": "^12.7.8",
    "typescript": "3.5.3"
  }
}
```

Running npm install again and then trying `ts-node p2pkh.ts` worked just fine after that. 

If that's the case I can submit a PR with this fix.

**Comment by rkalis** [comment]
Fixed by #37
