### ISSUE TITLE
Automatic UTXO selection

### ISSUE THREAD

**Issue by nyusternie** [Bitcoin-com/cashscript#75]
Looks like there might be an issue with the automatic UTXO selection.

I've been running test campaigns for Mecenas Oracle for a few weeks now. Some of the campaigns have exhausted their funds, so they're erroring as insufficient (which is find), however, at least one was re-funded by me, but it too is failing.

```
Contract address  : bitcoincash:prjtvqz9rdc0vqwzhf5zknf990vs752h4chmme9ezc
Contract opcount  : 99
Contract bytesize : 244
Contract balance  : 980262
Contract UTXOs    : [ { txid:
     '344c6f69881705c19ebc0f18c45c4e20afdef73bb2de4e7c82b073e5906b039a',
    vout: 1,
    amount: 0.00925417,
    satoshis: 925417,
    height: 652136,
    confirmations: 1 },
  { txid:
     '0210fb3c255ef662532e349a2987517bb2691c087bcca156fce6533145609605',
    vout: 1,
    amount: 0.00054845,
    satoshis: 54845,
    height: 651010,
    confirmations: 1127 } ]
```

i have to explain just a bit. `0210fb3c255ef662532e349a2987517bb2691c087bcca156fce6533145609605` was the original source of funds and `344c6f69881705c19ebc0f18c45c4e20afdef73bb2de4e7c82b073e5906b039a` was the reup.

The daily payout amount is currently `72583`. So the orignal is insufficient, but the reup is more than enough, however, I'm getting this error:

```
{ Error: Transaction failed with reason: non-BIP68-final (code 64)
meep debug --tx=02000000019a036b90e573b0827c4edeb23bf7deaf204e5cc4180fbc9ec1051788696f4c3401000000fd43030c68f30900f4010000131b0100463044022030c1ce40e2f2cc9206e30ed63bdf10c87ed3fe4934b2049c8ab9db75ab9fdf43022047211018032eb7413fa750eccb8c431877bdfb441eab4abde5c4bc8df116f30841317d397b0a0355161430d5f20b329f520ab6f67ba2a412be668892d391e6376883dbdc153e90815154b304afb02e5801e155d9dd9a59af40f5f315d5089ca6d7412103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c1844d9101020000009d20e420d53668b0da3dbeb7e55254b8c2fabcb685035dfd4782c26d5794d1796951cc3c6b6031dc1c8207abe3d53ef6167c8f8b6746b89b88df03b7b6ee2e4d9a036b90e573b0827c4edeb23bf7deaf204e5cc4180fbc9ec1051788696f4c3401000000f402f4010379e5092103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c18414f34bfe06109b843544c720116b18245763d2e99414321194ed5b7c37dfe97d2f96aa51bf974e2652555579009c63567901697f77820134947f587f547f7701207f755b7a5b796e7c828c7f755d7aa87bbbad5a7a5b795779bb597a567a8763029000b2756702a200b275685879547f758176b175567aa2695779547f77547f7581567a9d567a587f778102d007537a8152795880041976a9147e567a7e0288ac7e7c537a947b9458800317a9147e537aa97e01877e7eaa87777767557a519d5579a97b8871ad6d6d5168e91e0e00000000009000000031324bdf12d10e082dd412efef82a8fc9afa1ecb5e7986ba23e19c3fca9b7a6668f3090041000000004cf402f4010379e5092103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c18414f34bfe06109b843544c720116b18245763d2e99414321194ed5b7c37dfe97d2f96aa51bf974e2652555579009c63567901697f77820134947f587f547f7701207f755b7a5b796e7c828c7f755d7aa87bbbad5a7a5b795779bb597a567a8763029000b2756702a200b275685879547f758176b175567aa2695779547f77547f7581567a9d567a587f778102d007537a8152795880041976a9147e567a7e0288ac7e7c537a947b9458800317a9147e537aa97e01877e7eaa87777767557a519d5579a97b8871ad6d6d51689000000002131b0100000000001976a914321194ed5b7c37dfe97d2f96aa51bf974e26525588ac06fc0c000000000017a914e4b600451b70f601c2ba682b4d252bd90f5157ae8768f30900 --idx=0 --amt=925417 --pkscript=a914e4b600451b70f601c2ba682b4d252bd90f5157ae87
    at Object.buildError (/root/causes/node_modules/cashscript/dist/util.js:106:16)
    at Transaction.<anonymous> (/root/causes/node_modules/cashscript/dist/Transaction.js:155:30)
    at Generator.throw (<anonymous>)
    at rejected (/root/causes/node_modules/cashscript/dist/Transaction.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'non-BIP68-final (code 64)',
  meep:
   'meep debug --tx=02000000019a036b90e573b0827c4edeb23bf7deaf204e5cc4180fbc9ec1051788696f4c3401000000fd43030c68f30900f4010000131b0100463044022030c1ce40e2f2cc9206e30ed63bdf10c87ed3fe4934b2049c8ab9db75ab9fdf43022047211018032eb7413fa750eccb8c431877bdfb441eab4abde5c4bc8df116f30841317d397b0a0355161430d5f20b329f520ab6f67ba2a412be668892d391e6376883dbdc153e90815154b304afb02e5801e155d9dd9a59af40f5f315d5089ca6d7412103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c1844d9101020000009d20e420d53668b0da3dbeb7e55254b8c2fabcb685035dfd4782c26d5794d1796951cc3c6b6031dc1c8207abe3d53ef6167c8f8b6746b89b88df03b7b6ee2e4d9a036b90e573b0827c4edeb23bf7deaf204e5cc4180fbc9ec1051788696f4c3401000000f402f4010379e5092103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c18414f34bfe06109b843544c720116b18245763d2e99414321194ed5b7c37dfe97d2f96aa51bf974e2652555579009c63567901697f77820134947f587f547f7701207f755b7a5b796e7c828c7f755d7aa87bbbad5a7a5b795779bb597a567a8763029000b2756702a200b275685879547f758176b175567aa2695779547f77547f7581567a9d567a587f778102d007537a8152795880041976a9147e567a7e0288ac7e7c537a947b9458800317a9147e537aa97e01877e7eaa87777767557a519d5579a97b8871ad6d6d5168e91e0e00000000009000000031324bdf12d10e082dd412efef82a8fc9afa1ecb5e7986ba23e19c3fca9b7a6668f3090041000000004cf402f4010379e5092103fb19e8f648f9901709cad8ff8a0659bc6356aa64eeb1c460aed468255838c18414f34bfe06109b843544c720116b18245763d2e99414321194ed5b7c37dfe97d2f96aa51bf974e2652555579009c63567901697f77820134947f587f547f7701207f755b7a5b796e7c828c7f755d7aa87bbbad5a7a5b795779bb597a567a8763029000b2756702a200b275685879547f758176b175567aa2695779547f77547f7581567a9d567a587f778102d007537a8152795880041976a9147e567a7e0288ac7e7c537a947b9458800317a9147e537aa97e01877e7eaa87777767557a519d5579a97b8871ad6d6d51689000000002131b0100000000001976a914321194ed5b7c37dfe97d2f96aa51bf974e26525588ac06fc0c000000000017a914e4b600451b70f601c2ba682b4d252bd90f5157ae8768f30900 --idx=0 --amt=925417 --pkscript=a914e4b600451b70f601c2ba682b4d252bd90f5157ae87' }
```

I just ran my script "manually", adding `.from([contractUtxos.find(utxo => utxo.satoshis === 1000000)])` and it went through just fine
https://explorer.bitcoin.com/bch/tx/344c6f69881705c19ebc0f18c45c4e20afdef73bb2de4e7c82b073e5906b039a

so I believe the problem is the UTXO selection, but I'm still unable to read the __meep__ output.

The fix is simple for me, I'll just check the satoshi value of each UTXO and select the one that has sufficient value, but I just want to bring this to your attention, as I'm sure you would rather have this done automatically.

Let me know if you need any more info..

**Comment by rkalis** [comment]
There's two things to keep in mind that are both a result of the UTXO-based model of BCH:

First, if you top up the contract, that is "new" UTXO for the contract, meaning you need to wait at least 144 blocks before that one can be spent by the contract.

Second, in your contract, you enforce (with `tx.hashOutputs`) that the contract can only send a transaction where one output is `pledge` amount, and one output is `change` amount. The contract calculates the change amount using `tx.value`, which is the **value of the UTXO**. And this is evaluated **for each UTXO separately**. 

So even if the combined UTXOs are big enough, if one of them isn't it still cannot execute the contract successfully. Because of this it is better to essentially view every UTXO as its own unique contract, and not to combine multiple UTXOs in one transaction. 

The original Mecenas contract addresses this shortcoming by adding an additional condition for when the remaining UTXO value is below the pledge amount:

```solidity
        int intValue = int(bytes(tx.value));

        if (intValue <= pledge + minerFee) {
            /* The contract has less value than the pledge, or equal.
             * The recipient must claim all of of it. */

            bytes8 amount1 = bytes8(intValue - minerFee);
            bytes34 out1 = new OutputP2PKH(amount1, recipient);
            require(hash256(out1) == tx.hashOutputs);
        } else {
            /* The contract has more value than the pledge. The recipient must
             * also add one change output sending the remaining coins back
             * to the contract.
             */

            bytes8 amount1 = bytes8(pledge);
            bytes8 amount2 = bytes8(intValue - pledge - minerFee);
            bytes34 out1 = new OutputP2PKH(amount1, recipient);
            bytes32 out2 = new OutputP2SH(amount2, hash160(tx.bytecode));
            require(hash256(out1 + out2) == tx.hashOutputs);
        }
```

Ask @KarolTrzeszczkowski about v1 of Mecenas to find out how he figured that out ;)

My advice regarding this in your contract is to add a similar condition (looks like you still have enough opcodes remaining). Keep in mind that this probably still needs some client-side code that checks whether it should send the full pledge amount (`.to(address, pledgeAmount)`) or the remaining balance (`.to(address, utxo.satoshis)`).

Alternatively, if you don't want to add that to the contract, you need the user to reclaim the "stuck" funds whenever necessary.

**Comment by nyusternie** [comment]
> if you top up the contract, that is "new" UTXO for the contract

yeah, that part I got

> And this is evaluated for each UTXO separately

okay, this i did **NOT** know; but now it makes sense

> probably still needs some client-side code

yeah, I'd rather just handle this from the client-side .. during a re-up, i'll reclaim the "active" UTXO and just add it to the user-provided value; and as you suggested, the contract will use just a "single" UTXO

thanks for the explanation 👍
